### PR TITLE
Fix to work on CentOS/RHEL

### LINKED ISSUE #17: Support for bash scripts on RHEL/CentOS
as RHEL/CentOS doesnt support bash scripts in `/etc/motd` one needs to branch code when you need bash scripts in motd.

As a solution, you could check for `#!` in first line and then render template to `/etc/profile.d/motd.sh` instead of `/etc/motd` if `platform_family?('rhel')`

### PR DESCRIPTION
**Pull request by philicious**
I made the necessary changes to work with RHEL derivates.

I tested it to work properly on Ubuntu and CentOS. However I didnt update your unit and serverspecs

fixes #17

### CODE REVIEW

**Comment by chr4** [comment]
Thanks for your contribution!
I think this will break support for all legacy RHEL versions that do not support `motd.sh`.
I'm only merging this if it can be guaranteed that this fix get's only deployed on machines supporting it.

**Comment by philicious** [comment]
@chr4 which RHEL versions are you refering to ? `/etc/profile.d/` should be supported by all imho

**Comment by chr4** [comment]
Ah, if I understand correctly `/etc/profile.d` is the system-wide bash `profile.d`? This has nothing to do with the "real" motd then I think. Your messages for examples should not be displayed when using a different shell than bash, right?

**Comment by philicious** [comment]
Uhm yes you are right. Its bash specific. In contrary to update-motd on Ubuntu, it doesnt "render" it into `/etc/motd` but rather executes it on login and thereby its displayed like `/etc/motd` would be. 
There is no other way of having dynamic motd on RHEL and this is the supposed way

**Comment by chr4** [comment]
Ok. This should be sperated then.
I'm not sure if this is applicable at all for this cookbook, but if so, then it should be a standalone recipe like `motd::bash_profile`.

**Comment by philicious** [comment]
Hm I dont see why it should be separated. The intention of the motd LWRP is to be used for dynamic motd only and this is how it works on RHEL.

**Comment by chr4** [comment]
Because you are not modifying the motd. You are modifying the system-wide `.bash-profile`.
This should not be mixed with the actual motd. But because it seems like your approach is the only way of handling this in RHEL, one can use the seperated recipe (which can be in this cookbook) to modify the system-wide bash profile accordingly.
It should be super-clear though (and therefore use something like a recipe name like `bash_profile`) that the modification is not actually writing the motd.

Sidenote: Using `/etc/profile.d/` is not restricted to RHEL, as other distributions use it, too.

**Comment by philicious** [comment]
yes. `/etc/profile.d` would also work on Ubuntu but as it has update-motd especially for this purpose I didnt change it.

Btw you would need a separate LWRP and not a recipe. 

However, personally, I would prefer a single LWRP `motd` which has same effect/result on all platforms mentioned in metatada.rb without having to use a different LWRP. Otherwise one would still need to branch in their code for different platforms when having heterogenous infrastructure.

What are your thoughts on this ?

**Comment by chr4** [comment]
You're right, it would be an LWRP in this case. 

That's exactly the point. Your approach would not have the same result on all platforms, as it would modify the motd on non-rhel systems, and the bash0-profile on rhel systems.

Another method would be to add something like an `use_bash_profile` ressource, that the caller can then set depending on the underlying system. Doesn't feel very clean, though.

**Comment by philicious** [comment]
Hm. I get your point. The actual result on the filesystem is different but the visual effect is the same. But when using this LWRP I care about the visual result and not how its implemented.

So..hm..I'm satisfied with how my PR works cross-platform with a single LWRP now. But of course you can refactor it to use a second LWRP :)

**Comment by chr4** [comment]
It's not the same result. It even only works if the users are all using bash.
You're welcome to use your own fork, but I do not consider this "production ready" for an upstream merge due to the elaborated reasons.

**Pull request closed without merging**
