### PR TITLE
Update cookbook to Chef 14.

### LINKED ISSUE #25: chef_handler cookbook has been deprecated, causing cookstyle to fail
Cookstyle fails with:

`ChefModernize/UnnecessaryDependsChef14: Don't depend on cookbooks made obsolete by Chef Infra Client 14+. These community cookbooks contain resources that are now included in Chef Infra Client itself. depends 'chef_handler', '= 3.0.3'`

The [chef_handle cookbook](https://supermarket.chef.io/cookbooks/chef_handler) has been deprecated and is no longer being maintained by Chef.

The chef client can now implement handlers out of the box: https://docs.chef.io/handlers/

I can make a PR with the necessary changes.

### PR DESCRIPTION
**Pull request by Lasering**
Fixes #25 

I ran [`cookstyle -a`](https://docs.chef.io/workstation/cookstyle/) which is the preferred way to fix linting in Chef cookbooks. I had to remove `.rubocop.yml` because it was causing collisions with the cookstyle (which is also implemented using rubocop).

I could simplify the cookbook even further by implementing a custom resource as mentioned in #24.

I bumped the major version because of the line `chef_version     '>= 14.0'` in `metadata.rb`

### CODE REVIEW

**Comment by Lasering** [comment]
@chr4 I cannot trigger a travis run, to check if everything is ok.

**Comment by chr4** [comment]
Thanks for the contribution! I'll look into setting up Github Actions for CI, so this is also fixed.

> I could simplify the cookbook even further by implementing a custom resource as mentioned in #24.

If you'd have time doing that, it would be greatly apprechiated!

**Comment by chr4** [comment]
I've set up Github actions (but without modifying the Rake tasks). Can you rebase this and see whether the tests work with your changes?

**Comment by Lasering** [comment]
> If you'd have time doing that, it would be greatly apprechiated!

Can I do it in this PR or do you want another one?

**Comment by chr4** [comment]
I'd leave that up to you - whatever fits best for you.

**Comment by Lasering** [comment]
I'll do it in this one. It makes more sense due to the major version.

**Comment by Lasering** [comment]
@chr4 CI is failing in a rake dependency, can you help?

**Comment by chr4** [comment]
Can you try rebasing on this branch? It fixes the compile error: https://github.com/chr4-cookbooks/motd/pull/27

**Comment by Lasering** [comment]
Rebased

**Comment by chr4** [comment]
Nice, seems to work!

**Comment by Lasering** [comment]
I can no longer run `cookstlyle -a` I'm having problems with bundler.

It would make things easier to just install chef-dk in github workflow, that way all the dependencies would already be set. Here is an example using Travis https://github.com/ist-dsi/cookbook-vault-certificate

[Also foodcritic has been deprecated](https://docs.chef.io/workstation/foodcritic/):

> Foodcritic is deprecated and should no longer be used for cookbook linting. Use Cookstyle instead which offers additional rules, violation autocorrection, Ruby linting, and a robust configuration system.

**Comment by chr4** [comment]
Totally in favor of `chef-dk` - I've not touched the tests for too long. Feel free to change it!

**Comment by Lasering** [comment]
I've made the changes but the github actions didn't start running.

**Comment by Lasering** [comment]
This should be it.

**Comment by chr4** [comment]
Wow, that was quick!

I've got a small suggestion: 
If this turns out to be a low hanging fruit, we should add Ubuntu 16.04 and 18.04 as well as Centos 7. (while Ubuntu 14.04 and Centos 6 are still supported, I'm fine with dropping those). Not sure about the LTS policy from Debian here. But if they also have one, we could add releases that are going to be supported for a while as well.

What do you think?

**Comment by Lasering** [comment]
I have very strong opinions on which OS versions to support or not. Since you are the maintainer, you know best which OSs on want to maintain, so I'm gonna leave that one for you.

This cookbook does not work in CentOS 7. In my organization we use it, but for CentOS 7 we had to do some extra sets. I can include them here.

**Comment by chr4** [comment]
Haha fair enough! I'm going to merge this, and I'll check support for the additional versions myself. Thank you so much! 

If you don't mind, I'd add you to the contributors list in the README?

**Comment by Lasering** [comment]
> If you don't mind, I'd add you to the contributors list in the README?
Thanks

**Comment by Lasering** [comment]
@chr4 will you release this in supermarket? I can help if necessary.

**Comment by chr4** [comment]
Sorry, my bad. I've released version `v1.0.0`! Let me know if there's problems.

Thanks again for the contribution!

**Pull request merged**
